# Generated by Django 2.1.15 on 2021-12-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='subTitle',
            field=models.CharField(blank=True, help_text='Postun alt başlığını giriniz.', max_length=500, null=True, verbose_name='Post alt başlığı'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Post Adı'),
        ),
    ]
