# Generated by Django 2.1.15 on 2021-12-29 21:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211229_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
