# Generated by Django 4.0 on 2022-02-11 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Post güncelleme tarihi'),
        ),
    ]
