# Generated by Django 4.0 on 2022-02-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postmodel_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Post güncelleme tarihi'),
        ),
    ]
