# Generated by Django 4.0 on 2022-03-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_postmodel_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user_rank',
        ),
    ]
