# Generated by Django 4.0.3 on 2022-04-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_miniposttagmodel_alter_postmodel_image_minipostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minipostmodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Mini postun resmini seçiniz.', null=True, upload_to='blog/mini_posts/', verbose_name='Mini post fotoğrafı '),
        ),
    ]
