# Generated by Django 4.0.4 on 2022-06-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_minipostmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='minipostmodel',
            name='category',
            field=models.TextField(blank=True, help_text='Mini post kategori', null=True, verbose_name='Mini post kategori'),
        ),
    ]
