# Generated by Django 2.1.15 on 2021-12-29 01:10

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMainCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Haberin ana kategori adı')),
                ('slug', models.SlugField(default='emptySlug')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Haberin Adı')),
                ('subTitle', models.CharField(blank=True, help_text='Haberin alt başlığını giriniz.', max_length=500, null=True, verbose_name='Haberin alt başlığı')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(help_text='Haberin yazısını giriniz.', verbose_name='Haberin Yazısı')),
                ('image', models.ImageField(blank=True, default='static_img/empty-post-img.png', help_text='Haberin resmini seçiniz.', null=True, upload_to='users/moderators/auth.User/newsPost', verbose_name='Haberin Fotoğrafı ')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Haberin oluşturulma tarihi')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Haberin güncelleme tarihi')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('post_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Haber sahibi')),
            ],
        ),
        migrations.CreateModel(
            name='NewsSubCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Haber alt kategori adı')),
                ('slug', models.SlugField(default='emptySlug')),
                ('mainCategoryName', models.ForeignKey(default=1, help_text='Alt kategorinin bağlı olduğu ana kategori adı.', on_delete=django.db.models.deletion.CASCADE, related_name='newsMainCategory_in_newsSubCategory', to='news.NewsMainCategoryModel', verbose_name='Bağlı olduğu ana kategori adı')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Haber etiket adı')),
                ('slug', models.SlugField(default='emptySlug')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsModel',
        ),
        migrations.AddField(
            model_name='newspostmodel',
            name='subCategory',
            field=models.ForeignKey(default=1, help_text='Haberin kategorisini seçiniz.', on_delete=django.db.models.deletion.CASCADE, related_name='newsSubCategory_in_post', to='news.NewsSubCategoryModel', verbose_name='Haber alt kategori'),
        ),
        migrations.AddField(
            model_name='newspostmodel',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Haberin etiketlerini seçiniz.', related_name='newsPostsTag', to='news.NewsTagModel', verbose_name='Haber Etiketleri'),
        ),
    ]
