# Generated by Django 2.1.15 on 2021-12-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211229_0410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssubcategorymodel',
            name='mainCategoryName',
        ),
        migrations.DeleteModel(
            name='NewsMainCategoryModel',
        ),
    ]
