# Generated by Django 4.0 on 2022-01-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserSiteSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_theme', models.BooleanField(default=False, verbose_name='Koyu tema aiktif mi?')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Post sahibi')),
            ],
        ),
        migrations.DeleteModel(
            name='MainSerializersModel',
        ),
    ]
