# Generated by Django 2.1.15 on 2021-12-25 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import studentUsers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=studentUsers.models.upload_certificate_image)),
                ('imageDec', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sertifika açıklaması')),
            ],
            options={
                'verbose_name': 'Student >> Certificate',
            },
        ),
        migrations.CreateModel(
            name='StudentEducationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationInfo', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Lise'), (1, 'Üniversite'), (2, 'Erasmus'), (3, 'Yüksek Lisans'), (4, 'Doktora')], max_length=9, verbose_name='Eğitimi')),
                ('startedDate', models.DateField(blank=True, null=True, verbose_name='Başlangıç tarihi')),
                ('finishedDate', models.DateField(blank=True, null=True, verbose_name='Bitiş tarihi')),
                ('educationName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eğitim adı')),
                ('educationPosition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eğitim pozisyon adı')),
                ('educationDesc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Eğitim açıklaması')),
            ],
            options={
                'verbose_name': 'Student >> Education',
            },
        ),
        migrations.CreateModel(
            name='StudentExperiencesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experienceInfo', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Lise'), (1, 'Üniversite'), (2, 'Erasmus'), (3, 'Yüksek Lisans'), (4, 'Doktora')], max_length=9, verbose_name='Deneyimi')),
                ('startedDate', models.DateField(blank=True, null=True, verbose_name='Başlangıç tarihi')),
                ('finishedDate', models.DateField(blank=True, null=True, verbose_name='Bitiş tarihi')),
                ('companyName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şirket adı')),
                ('experienceDesc', models.TextField(blank=True, max_length=500, null=True, verbose_name='İş deneyimi açıklaması')),
            ],
            options={
                'verbose_name': 'Student >> Experience',
            },
        ),
        migrations.CreateModel(
            name='StudentForeignLangModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yabancı dil adı')),
                ('foreignLangRank', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'A1'), (1, 'A2'), (2, 'B1'), (3, 'B2'), (4, 'C1'), (5, 'C2')], max_length=11, verbose_name='Yabancı dil derecesi')),
                ('langDesc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Yabancı dil açıklaması')),
            ],
            options={
                'verbose_name': 'Student >> Foreign Language',
            },
        ),
        migrations.CreateModel(
            name='StudentImageGalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=studentUsers.models.upload_image_gallery)),
                ('imageDec', models.CharField(blank=True, max_length=150, null=True, verbose_name='Resim açıklaması')),
            ],
            options={
                'verbose_name': 'Student >> Image Gallerie',
            },
        ),
        migrations.CreateModel(
            name='StudentInterestedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestName', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlgi adı')),
            ],
            options={
                'verbose_name': 'Student >> Interested',
            },
        ),
        migrations.CreateModel(
            name='StudentTalentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talentInfo', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Programlama Dilleri'), (1, 'Programlar')], max_length=3, verbose_name='Yeteneği/Etkinliği')),
                ('talentRankInfo', multiselectfield.db.fields.MultiSelectField(choices=[(0, '0'), (1, '10'), (2, '20'), (3, '30'), (4, '40'), (5, '50'), (6, '60'), (7, '70'), (8, '80'), (9, '90'), (10, '100')], max_length=22, verbose_name='Yetenek/Etkinlik derecesi')),
                ('talentName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yetenek/Etkinlik adı')),
                ('talentDesc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Yetenek/Etkinlik açıklaması')),
            ],
            options={
                'verbose_name': 'Student >> Talent',
            },
        ),
        migrations.CreateModel(
            name='StudentUserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField(choices=[(1, 'Aktif'), (0, 'Pasif')], default=1, verbose_name='Öğrenci aktif mi?')),
                ('studentId', models.CharField(blank=True, max_length=9, null=True, verbose_name='Öğrenci ID')),
                ('backImage', models.ImageField(blank=True, default='static/main-logo.png', null=True, upload_to='studentUsers/background-image', verbose_name='Arka plan fotoğrafı')),
                ('profImage', models.ImageField(blank=True, default='static/Admin_Resim.jpg', null=True, upload_to='studentUsers/profile-image', verbose_name='Profil fotoğrafı')),
                ('departmentName', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bölüm adı')),
                ('smallDesc', models.TextField(blank=True, default='İstanbul Sabahattin Zaim Üniversitesi yazılım mühendisliği 4.sınıf öğrencisiyim.', max_length=500, null=True, verbose_name='Kişinin kısa açıklaması')),
                ('bioDesc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Kişinin biografi açıklaması')),
                ('departmentClass', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sınıfı')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon numarası')),
                ('adress', models.TextField(blank=True, max_length=300, null=True, verbose_name='Adres bilgisi')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Doğum tarihi')),
                ('studentUserSelfInfo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Doğum tarihi'), (1, 'Telefonu'), (2, 'Açık adresi')], max_length=5, null=True, verbose_name='Kişisel Bilgilerim \n( Sayfada görünmesini istediğiniz bilgileri seçiniz.)')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('studentUserSocialMedia', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'İnstagram'), (1, 'Twitter'), (2, 'Facebook'), (3, 'Linkedn'), (4, 'Whatsapp')], max_length=9, null=True, verbose_name='İletişim bilgileri')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profil Sahibi')),
            ],
            options={
                'verbose_name': 'Student Profile',
            },
        ),
        migrations.AddField(
            model_name='studenttalentsmodel',
            name='studentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_student_user', to='studentUsers.StudentUserProfileModel'),
        ),
        migrations.AddField(
            model_name='studentinterestedmodel',
            name='studentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_student_user', to='studentUsers.StudentUserProfileModel'),
        ),
        migrations.AddField(
            model_name='studentimagegallerymodel',
            name='studentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery_student_user', to='studentUsers.StudentUserProfileModel'),
        ),
        migrations.AddField(
            model_name='studentforeignlangmodel',
            name='studentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_lang_student_user', to='studentUsers.StudentUserProfileModel'),
        ),
        migrations.AddField(
            model_name='studentexperiencesmodel',
            name='studentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_student_user', to='studentUsers.StudentUserProfileModel'),
        ),
        migrations.AddField(
            model_name='studenteducationsmodel',
            name='studentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_student_user', to='studentUsers.StudentUserProfileModel'),
        ),
        migrations.AddField(
            model_name='studentcertificatesmodel',
            name='studentUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_student_user', to='studentUsers.StudentUserProfileModel'),
        ),
    ]
