# Generated by Django 2.1.15 on 2021-12-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuserprofilemodel',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Aktif'), (0, 'Pasif')], db_column='sadasd', default=1, help_text='denemememe', verbose_name='Öğrenci aktif mi?'),
        ),
    ]
