# Generated by Django 2.1.15 on 2021-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0002_auto_20211225_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuserprofilemodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='studentuserprofilemodel',
            name='kjhfgl',
            field=models.IntegerField(choices=[(1, 'Aktif'), (0, 'Pasif')], default=1, help_text='denemememe', verbose_name='Öğrenci aktif mi?'),
        ),
    ]
