# Generated by Django 2.1.15 on 2021-12-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0003_auto_20211225_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuserprofilemodel',
            old_name='kjhfgl',
            new_name='abc',
        ),
    ]
