# Generated by Django 2.1.15 on 2021-12-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0004_auto_20211225_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuserprofilemodel',
            name='abc',
        ),
        migrations.AddField(
            model_name='studentuserprofilemodel',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Aktif'), (0, 'Pasif')], default=1, verbose_name='Öğrenci aktif mi?'),
        ),
    ]
