# Generated by Django 2.1.15 on 2021-12-25 17:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0005_auto_20211225_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuserprofilemodel',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentexperiencesmodel',
            name='experienceInfo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'İş Deneyimleri'), (1, 'Staj Deneyimleri')], max_length=3, verbose_name='Deneyimi'),
        ),
        migrations.AlterField(
            model_name='studentuserprofilemodel',
            name='studentUserSocialMedia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'İnstagram'), (1, 'Twitter'), (2, 'Facebook'), (3, 'Linkedn'), (4, 'Github'), (5, 'Whatsapp')], max_length=11, null=True, verbose_name='İletişim bilgileri'),
        ),
    ]
