# Generated by Django 2.1.15 on 2021-12-25 23:24

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0006_auto_20211225_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgLangModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progLangRankInfo', multiselectfield.db.fields.MultiSelectField(choices=[(0, '0'), (1, '10'), (2, '20'), (3, '30'), (4, '40'), (5, '50'), (6, '60'), (7, '70'), (8, '80'), (9, '90'), (10, '100')], max_length=22, verbose_name='Programlama dili derecesi')),
                ('progLangName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Programlama dili adı')),
                ('progLangDesc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Programlama dili açıklaması')),
                ('studentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porgLang_student_user', to='studentUsers.StudentUserProfileModel')),
            ],
            options={
                'verbose_name': 'Student >> Programming Language',
            },
        ),
        migrations.CreateModel(
            name='StudentProgTalentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progTalentRankInfo', multiselectfield.db.fields.MultiSelectField(choices=[(0, '0'), (1, '10'), (2, '20'), (3, '30'), (4, '40'), (5, '50'), (6, '60'), (7, '70'), (8, '80'), (9, '90'), (10, '100')], max_length=22, verbose_name='Program derecesi')),
                ('progTalentName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Program adı')),
                ('progTalentDesc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Program açıklaması')),
                ('studentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porgTalent_student_user', to='studentUsers.StudentUserProfileModel')),
            ],
            options={
                'verbose_name': 'Student >> Programs Talent',
            },
        ),
        migrations.RemoveField(
            model_name='studenttalentsmodel',
            name='studentUser',
        ),
        migrations.DeleteModel(
            name='StudentTalentsModel',
        ),
    ]
