# Generated by Django 4.0 on 2022-01-22 20:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0010_alter_studentcertificatesmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuserprofilemodel',
            name='studentUserSelfInfo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Doğum tarihi', 'Doğum tarihi'), (1, 'Telefonu'), (2, 'Açık adresi')], max_length=16, null=True, verbose_name='Kişisel Bilgilerim \n( Sayfada görünmesini istediğiniz bilgileri seçiniz.)'),
        ),
    ]
