# Generated by Django 4.0 on 2022-01-22 20:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0011_alter_studentuserprofilemodel_studentuserselfinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducationsmodel',
            name='educationInfo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lise', 'Lise'), ('Üniversite', 'Üniversite'), ('Erasmus', 'Erasmus'), ('Yüksek Lisans', 'Yüksek Lisans'), ('Doktora', 'Doktora')], max_length=45, verbose_name='Eğitimi'),
        ),
        migrations.AlterField(
            model_name='studentexperiencesmodel',
            name='experienceInfo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('İş Deneyimi', 'İş Deneyimi'), ('Staj Deneyimi', 'Staj Deneyimi')], max_length=25, verbose_name='Deneyimi'),
        ),
        migrations.AlterField(
            model_name='studentforeignlangmodel',
            name='foreignLangRank',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=17, verbose_name='Yabancı dil derecesi'),
        ),
        migrations.AlterField(
            model_name='studentproglangmodel',
            name='progLangRankInfo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', '0'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=32, verbose_name='Programlama dili derecesi'),
        ),
        migrations.AlterField(
            model_name='studentprogtalentmodel',
            name='progTalentRankInfo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', '0'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('90', '90'), ('100', '100')], max_length=32, verbose_name='Program derecesi'),
        ),
        migrations.AlterField(
            model_name='studentuserprofilemodel',
            name='studentUserSelfInfo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Doğum tarihi', 'Doğum tarihi'), ('Telefon', 'Telefon'), ('Açık adres', 'Açık adres')], max_length=31, null=True, verbose_name='Kişisel Bilgilerim \n( Sayfada görünmesini istediğiniz bilgileri seçiniz.)'),
        ),
        migrations.AlterField(
            model_name='studentuserprofilemodel',
            name='studentUserSocialMedia',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('İnstagram', 'İnstagram'), ('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Linkedn', 'Linkedn'), ('Github', 'Github'), ('Whatsapp', 'Whatsapp')], max_length=50, null=True, verbose_name='İletişim bilgileri'),
        ),
    ]
