# Generated by Django 4.0 on 2022-02-24 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentUsers', '0012_alter_studenteducationsmodel_educationinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuserprofilemodel',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcıyı takip edenler'),
        ),
    ]
