# Generated by Django 4.0 on 2022-02-24 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentUsers', '0013_studentuserprofilemodel_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuserprofilemodel',
            name='followers',
        ),
        migrations.AddField(
            model_name='studentuserprofilemodel',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcının takip ettikleri'),
        ),
    ]
