# Generated by Django 4.0 on 2022-03-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentUsers', '0014_remove_studentuserprofilemodel_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuserprofilemodel',
            name='user_rank',
            field=models.CharField(default=0, max_length=999, verbose_name='Kullanıcı rütbesi'),
        ),
    ]
