# Generated by Django 4.0.3 on 2022-04-26 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Post oluşturulma tarihi'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Post güncelleme tarihi'),
        ),
    ]
