# Generated by Django 4.0 on 2022-02-14 20:55

import ckeditor_uploader.fields
import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(default='emptySlug')),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Etiket adı')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('slug', models.SlugField(default='emptySlug')),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Topik Adı')),
                ('slug', models.SlugField(default='emptySlug')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tartışma Adı')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Tartışma yazısını giriniz.', null=True, verbose_name='Tartışma Yazısı')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Tartışma oluşturulma tarihi')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('discussion_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Tartışma sahibi')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='discussion_likes', to=settings.AUTH_USER_MODEL, verbose_name='Tartışma beğenenler')),
                ('subCategory', models.ForeignKey(default=1, help_text="Tartışmanın'un Kategorisini Seçiniz.", on_delete=django.db.models.deletion.CASCADE, related_name='maincategory_in_discussion', to='discussions.maincategorymodel', verbose_name='Tartışma Kategorisi')),
                ('tag', models.ManyToManyField(blank=True, help_text='Tartışma etiketlerini seçiniz.', related_name='discussionTag', to='discussions.TagModel', verbose_name='Tartışma Etiketleri ')),
                ('topic', models.ForeignKey(default=1, help_text="Tartışmanın'un Topiğini Seçiniz.", on_delete=django.db.models.deletion.CASCADE, related_name='topic_in_discussion', to='discussions.topicmodel', verbose_name='Topik Adı')),
            ],
        ),
    ]
