# Generated by Django 4.0 on 2022-02-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_remove_discussionsmodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionsmodel',
            name='topic',
            field=models.ForeignKey(default=1, help_text="Tartışmanın'un Topiğini Seçiniz.", on_delete=django.db.models.deletion.CASCADE, related_name='topic_in_discussion', to='discussions.topicmodel', verbose_name='Topik Adı'),
        ),
    ]
