# Generated by Django 4.0 on 2022-02-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_discussionsmodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategorymodel',
            name='image',
            field=models.ImageField(blank=True, default='static_img/empty-post-img.png', help_text='Kategorinin ikonunu seçiniz.', null=True, upload_to='static/icons/discussions', verbose_name='Kategori İkonu '),
        ),
    ]
