# Generated by Django 4.0 on 2022-02-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_maincategorymodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategorymodel',
            name='image',
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='image',
            field=models.ImageField(blank=True, default='static_img/empty-post-img.png', help_text='Topik ikonunu seçiniz.', null=True, upload_to='static/icons/discussions', verbose_name='Topik İkonu '),
        ),
    ]
