# Generated by Django 4.0 on 2022-02-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_alter_topicmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmodel',
            name='image',
        ),
    ]
