# Generated by Django 4.0 on 2022-02-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_remove_topicmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='image',
            field=models.ImageField(blank=True, default='static/light_logo.png', help_text='Topik ikonunu seçiniz.', null=True, upload_to='static/icons/discussions', verbose_name='Topik İkonu '),
        ),
    ]
